### PR TITLE
Feat/v2 update bonding share

### PR DESCRIPTION
**Pull request by zgorizzo69**

### CODE REVIEW

**Comment by Zequez** [comment]
Fixed a TypeScript error that was happening in common.
Added loading indicator for the LP balance
Tried to add the migration button conditionally but I was getting an error saying it couldn't estimate gas limit so I disabled it;; see if you can figure out, I'm going to eat dinner and continue later.

**Review by 0x4007 — APPROVED** [review]

**Comment by 0x4007** [comment]
@zgorizzo69 @Zequez you guys should add gpg signing in the future for this stuff. 
Screen Shot 2021-07-31 at 01 41 18

**Comment by pavlovcik** [comment]
The UI is broken

**Review by 0x4007 — COMMENTED** [review]
Not sure what's wrong with the migrate button but it throws errors

**Pull request merged**
